### ISSUE TITLE
gulp package-osx not working on Mac OS Sierra 10.12.1

### ISSUE THREAD

**Issue by dbradleyfl** [itsnauman/electron-menubar-boilerplate#1]
Everything else about this boilerplate works great. Must run gulp package-osx twice to get a release folder. Once release folder appears and app is clicked you get this error:

Uncaught Exception:
Error: Cannot find module 'menubar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/devon/Dev/electron-menubar/release/GitBox.app/Contents/Resources/app/index.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/Users/devon/Dev/electron-menubar/release/GitBox.app/Contents/Resources/atom.asar/browser/init.js:158:8)

Looks like 'gulp-symdest' has been deprecated. Could be what is breaking the build?

![screen shot 2016-12-10 at 10 16 36 am](https://cloud.githubusercontent.com/assets/5935459/21075258/d1a78af2-bec1-11e6-940e-12e1d05f4b58.png)

**Comment by awitherow** [comment]
Same errors with me as well, just wanted to jump in on the convo. Any way I can help?

**Comment by dbradleyfl** [comment]
@awitherow @itsnauman I think it is a problem with "gulp build-production", but I'm not sure. There are a lot of packages used from building production until packaging with gulp-atom-electron and very few error messages to go off of.

The easiest way I found around the issue was to rewrite 'gulp package' tasks to use npm package 'electron-packager' instead of 'gulp-atom-electron'. Didn't use the 'gulp build-production', or the build folder at all. I'm not sure the consequences of doing it that way (file size maybe?), but it works for now.

I also saw that this boilerplate is a fork of [Jolteon](https://github.com/vulpino/jolteon), but the gulp file seems to work when I clone that boilerplate.

Any ideas @awitherow?

**Comment by awitherow** [comment]
Sorry for the late response @dbradleyfl . I had given up on developing my app using this boilerplate since I hadn't heard anything (but it appears I just need to check my email more often! 😅  )

Would you want to open a PR and push the changes with the use of electron-packager instead?

Considering @itsnauman did not respond back, might just use Jolteon myself, as the only real difference here seems to be SASS support, which I can live without.
